### ISSUE TITLE
Symlinks

### ISSUE THREAD

**Issue by stuartmcalpine** [LSSTDESC/dataregistry#110]
Currently there is a `copy` attribute in the `register_dataset` which is `True` or `False` depending if you want to copy the data of make a symlink. But we don't currently use the symlink aspect anywhere. Should we keep this idea?

**Comment by JoanneBogart** [comment]
We ought to be able to cover this case with `location_type == "external"`.  The value for `url` could be 
`file:///<abs_path_to_old_location>`
