### ISSUE TITLE
Advance Python version in CI

### ISSUE THREAD

**Issue by JoanneBogart** [LSSTDESC/dataregistry#121]
We're currently using 3.9 but standard DESC kernel is now 3.10 and LSST distributions use 3.11.   We should be testing in one or both of 3.10, 3.11

**Comment by stuartmcalpine** [comment]
Yes I agree, I left out lots of Python versions originally as to not have so many github actions running every time we made changes at the beginning during the heavy development phase.

I will add in lots more versions, maybe just for pull requests and not every push

**Comment by JoanneBogart** [comment]
We should have 3.10 and 3.11 anyway. Do you think we need others?

**Comment by stuartmcalpine** [comment]
Addressed in #131
