### ISSUE TITLE
Querying between tables

### ISSUE THREAD

**Issue by stuartmcalpine** [LSSTDESC/dataregistry#135]
When querying on a dataset, but only returning columns from another table, it will fail. You currently need at least one dataset column in the requested list for it to work.

e.g.,

f = datareg.Query.gen_filter("dataset.dataset_id", "==", d_id_2)

results = datareg.Query.find_datasets(
        [
            "dataset.name",
            "execution.execution_id",
            "execution.description",
            "execution.site",
            "execution.name",
        ],
        [f],
        return_format="cursorresult",
    )

If it don't have `dataset.name`, the query will return the wrong details. Because it gets the table links from the property_names in find_datasets, is that what we want?

**Comment by JoanneBogart** [comment]
No, definitely not what we want.   We need to add in any tables referenced in filters which aren't already there.

**Comment by stuartmcalpine** [comment]
Addressed in #137
