### ISSUE TITLE
Concerning register and replace functions and certain columns in the dataset table

### ISSUE THREAD

**Issue by JoanneBogart** [LSSTDESC/dataregistry#144]
Topics to be discussed:

- Do we need `replace_date` and `replace_uid` given that, under normal circumstances, `delete_date` and `delete_uid` will have just been updated? How do the `delete_` columns interact with `is_overwritten`?

- We have to enforce suitable constraints in code on `relative_path` since we can't do it with database constraints.

- Prefer not to halt user's execution due to minor database inconsistencies not having to do with the current process (as long as continuing is not going to compound the problem).

**Comment by stuartmcalpine** [comment]
> Do we need replace_date and replace_uid given that, under normal circumstances, delete_date and delete_uid will have just been updated? 

Yes this is right, they are redundant, given we delete the dataset during replace. We can add another bit to the status field (going to `valid`, `deleted`, `archived`, `replaced`)?

> How do the delete_ columns interact with is_overwritten?

Currently `delete()` only checks if the dataset is `valid` and not `deleted`, so will need to add a check to make sure its not also a `replaced` dataset. Is this what you mean?

> We have to enforce suitable constraints in code on relative_path since we can't do it with database constraints.

Ok, a pre-register check on if the relative path is available, will do. To make things simple, if the auto generated relative path is not available (I find this hard to see happening), raise and error saying they have to chose a manual relative path?

> Prefer not to halt user's execution due to minor database inconsistencies not having to do with the current process (as long as continuing is not going to compound the problem).

Not sure what you mean here

**Comment by JoanneBogart** [comment]
> Currently delete() only checks if the dataset is valid and not deleted, so will need to add a check to make sure its not also a replaced dataset. Is this what you mean?
Yes, I guess so. The check is just against the value 1, I believe (valid and not archived and not deleted) so if we use another bit to mean replaced the check against 1 would still be correct, but not very clear what's going on.  We should give it a name (VALID_ONLY ?), meaning only the "valid" bit is set and everything else is clear, and compare against that.

**Comment by JoanneBogart** [comment]
> Ok, a pre-register check on if the relative path is available, will do. To make things simple, if the auto generated relative path is not available (I find this hard to see happening), raise and error saying they have to chose a manual relative path?
Yes.

**Comment by JoanneBogart** [comment]
> Prefer not to halt user's execution due to minor database inconsistencies not having to do with the current process (as long as continuing is not going to compound the problem).

In particular I was thinking of the error thrown when more than one previous dataset is discovered. That code is gone now, but the idea is still worth consideration.

If a user operation is about to fail because the database is in some unexpected state, it may be possible and desirable to proceed anyway.  Perhaps the database irregularity can be fixed by whatever detected it.  Or maybe it's harmless. Whether this is a good idea or not depends on how the unexpected state arose: if it's due to a bug or bad design this could prolong the process of finding and fixing it. So even if the code doesn't halt it should at least issue a warning message.

**Comment by stuartmcalpine** [comment]
Started to address these in #142
