### ISSUE TITLE
Symlinks

### ISSUE THREAD

**Issue by stuartmcalpine** [LSSTDESC/dataregistry#145]
There is still a `copy` argument in `register` that I think was designed for symlinks. But we don't actually use it right? Should we get rid of it?

Also, if the user registers via a `old_location`pointing to a symlink, I presume it still works?

**Comment by JoanneBogart** [comment]
We should be consistent.  Either we allow symlinks or we don't; it shouldn't depend on whether or not the dataset is copied.  My inclination is that they should not be allowed

**Comment by stuartmcalpine** [comment]
Addressed in #147
