### ISSUE TITLE
Don't add version to the filename suffix

### ISSUE THREAD

**Issue by stuartmcalpine** [LSSTDESC/dataregistry#155]
Currently files when they are registered with an automatically generated name have the version appended to the end of the file name.

This in theory messes up the filename suffix, if an application was to use that.

Could:
- Put dataset files also into directories first with the auto generated name and version, then put the file into that directory
- Name the directories based on the executions and have the files go into their execution folders (however as you can append datasets to executions after, theres no guarantee of filename conflicts later)

**Comment by JoanneBogart** [comment]
I'd like to also make a somewhat related change to ensure that automatically-generated paths don't clash with user-supplied paths:  we make a subdirectory, say called `.gen_paths`, under the `owner` level, and all generated names go under there.   We would also need to disallow any user paths starting with that string.

**Comment by stuartmcalpine** [comment]
Started addressing this in #159 

> I'd like to also make a somewhat related change to ensure that automatically-generated paths don't clash with user-supplied paths: we make a subdirectory, say called .gen_paths, under the owner level, and all generated names go under there. We would also need to disallow any user paths starting with that string.

I have added this to the PR. Now auto generated relative paths start with a `.gen_paths` directory. There is also a check making sure users cannot start their relative paths with that directory
