### ISSUE TITLE
Return statement indentation in Registrar._handle_data

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/dataregistry#27]
I think the indentation on this line might be wrong:

https://github.com/LSSTDESC/dataregistry/blob/9631093d17301c36d1846aec47ca4c0b62040ebb/src/dataregistry/registrar.py#L125

if old_location is not True there will be no return value.

Sorry for the noise if not!

**Comment by JoanneBogart** [comment]
I think you're right. Thanks for catching it!

**Comment by stuartmcalpine** [comment]
Thanks Joe, I've put this in #29
