### ISSUE TITLE
Figure out what's holding up deploy of doc pages

### ISSUE THREAD

**Issue by JoanneBogart** [LSSTDESC/dataregistry#34]
The public pages have not been updated since the first deployment. This is holding up the beta release.

**Comment by JoanneBogart** [comment]
It seems to have fixed itself.  It would be good to understand why.

**Comment by stuartmcalpine** [comment]
This looks to be resolved.

For info, the pages are built automatically with push and pull requests. But new docs are only deployed to github pages if the Docs CI is manually triggered via workflow_dispatch on the main branch.
