### ISSUE TITLE
Installation documentation may not be complete

### ISSUE THREAD

**Issue by JoanneBogart** [LSSTDESC/dataregistry#36]
I tried blindly following the installation instructions as an exceedingly naive user might:

First I tried it on my home Mac from a very bare-bones python environment (just what you get with miniconda).  It failed because it couldn't find the executable `pg_config`, needed to build psycopg2 from source.

Next I tried it on Perlmutter without doing any sort of set up at all, and it failed because there is no pip!

Then I tried it on Perlmutter after first setting up the DESC standard Python kernel (without stack). That built all right (psycopg2 is already included as well as the `pg_config` executable), but it was unable to install because I didn't have permission. 

These are not problems any of our users are likely to have but, even so, maybe we should say a little more.  At the very least somewhere we should state that the package is only usable currently at NERSC.

In the section **Authenticating with the database** I'd prefer a name for the config file that doesn't include "reader".  Maybe `~/.config_reg_access` ?

**Comment by stuartmcalpine** [comment]
These should be covered with #39 , we can move this issue discussion to #38
