### ISSUE TITLE
Add `dataregistry` to `desc-python`

### ISSUE THREAD

**Issue by stuartmcalpine** [LSSTDESC/dataregistry#56]
Should we request to add `dataregistry` to the `desc-python` environment.

Maybe after beta testing is complete?

**Comment by JoanneBogart** [comment]
After just now following all the instructions needed to install dataregistry and incorporate it in my own jupyter kernel, I heartily agree that dataregistry belongs in the `desc-python` environment.  This is just too much overhead to subject people to.   

I have to say the process, though many steps long, generally went smoothly. The only thing I would change on our doc page http://lsstdesc.org/dataregistry/installation.html would be to suggest that, if you expect to use dregs from jupyter, the `conda create` line should also include ipykernel

**Comment by JoanneBogart** [comment]
As of Sept. 27, 2024, dataregistry is part of python-bleed
