### ISSUE TITLE
The root path

### ISSUE THREAD

**Issue by stuartmcalpine** [LSSTDESC/dataregistry#57]
The user technically has the option to specify `root_dir` when starting up the `Registrar` object. Which is if they wanted to use their own space on their laptop etc, or somewhere not in the `DEFAULT_ROOT`.

Does this then create problems as we don't know where the data necessarily is? We only store relative paths in the database.

**Comment by JoanneBogart** [comment]
We definitely need better control of root path.  To start (not exactly addressing the question you've asked) I think we should institute a scheme similar to GCRCatalogs.  That is

- dataregistry package includes a configuration file with default values for `DEFAULT_ROOT` by site.  So far, we only have one site: NERSC.
- by default site will be NERSC, but we write code to look for an environment variable, say `DATAREGISTRY_SITE`, which can override that default.
- if site is not NERSC (or any other well-known site with an entry in the configuration file), user _must_ supply a value for `root_dir`

To take care of the case you mentioned, we could  insist that, for writers, if your connection parameters are referring to the standard postgres db at NERSC, you _must_ use the NERSC `DEFAULT_ROOT`.   But we have to think about how this might interact with remote users. Is it adding additional restrictions on them?   So far, I haven't been able to imagine a procedure for them to register new datasets, other than through some server at NERSC.  (We could perhaps first transfer their local dataset to NERSC via globus, then have some process running at NERSC to do the actual registration.  But then that process would be following all the rules.)

One way or another, I think we need to enforce, at least for writers, that one uses the standard postgres db if and only if you're also using the NERSC `DEFAULT_ROOT`.  

I'm not

**Comment by JoanneBogart** [comment]
Also we need to provide a way for people to retrieve `root_dir` so they can form the full path if they want to read a dataset they or someone else has registered.  Assuming some day we might want to mirror some or all datasets at another site, we need a concept of per-site default.   Registrar could have a method which returns the default for the current site - which for now is always NERSC.

**Comment by stuartmcalpine** [comment]
We have addressed the "sites" for the root dir and that is now in the main branch.

In #87 I have added the root_dir to the dataset table, so we can keep track of where the dataset was originally registered.

We still don't force a `root_dir` based on the database you connect to, which is the last open question for this issue.
