### ISSUE TITLE
Just one Production across schemas

### ISSUE THREAD

**Issue by JoanneBogart** [LSSTDESC/dataregistry#62]
In the directory hierarchy of datasets, "production" for each schema should be a sym link to the DESC protected shared area, ```/global/cfs/cdirs/lsst/shared```
Production datasets (and only those) may be dependencies of datasets in any schema, so entries for them probably belong in a schema of their own (along with all the other tables belonging to current schemas). 
Code will have to be revamped to handle any references to production datasets specially, since they will have to be qualified by schema name.  
The structure of the `dependency` table will have to change to allow the possibility of a dependency dataset which is in the production schema, even if the dataset depending on it is not (add another foreign key column referencing `production.dataset.dataset_id`?)  Or maybe better just add a new table `production_dependency`.
Something similar might have to be done about the foreign key reference dataset.execution_id. Or maybe not since I would expect production datasets to only be created by production executions. However at some point we need to think about how to allow someone to move a dataset from one of the other owner types to production. It is going to be difficult, or at the very least tedious, to update all relations correctly.

**Comment by stuartmcalpine** [comment]
Started to look at this in #74 

Some initial thoughts questions:

1) The provenance table is part of the schema. So if we have a production schema, is there a risk of versions going out of sync?

Should we have just provenance for the database, does that mean it has to be in its own schemea? Or maybe the provenance is just in the production schema? 

2) Currently owner_type is unchanged. However it will raise an error if you try to assign owner_type="production" to anything other than the production schema. And also raise an error anything going into production that is not owner_type == "production"

3) sqllite can't have multiple schemas, this means we can't have a production schema for that backend

4) Think about ways to query between schemas

**Comment by JoanneBogart** [comment]
For 1. - each schema has its own version tracking in its provenance table.  It's up to us as maintainers to ensure that the production schema is compatible with any schema someone might want to access along with it in the same session. Perhaps at connection time we can check and issue a warning if they're not compatible (once we figure out what that means).
For 3. - I had forgotten, but actually sqlite can have multiple schemas, sort of. See https://www.sqlite.org/lang_attach.html .    I'm not sure whether we can make use of this or not (and, if we can, if it's worth the effort).
For 4. - I think all we need to support are queries that involve the original schema (the one coming from the DbConnection call) and the well-known production schema.  
For 5. - I don't have strong feelings about the name; so far I haven't found anything wrong with sticking with "production".   Whatever we decide, it should be a constant, probably declared in db_basic, which is available to the rest of the code, e.g.
`PRODUCTION_SCHEMA="production"`

**Comment by stuartmcalpine** [comment]
@JoanneBogart if we want query support for the production schema whilst connected to the original schema, I'm not sure how this would work.

I'm guessing, for a given query on the dataset name for example, it would search both the current schema and the production schema and return the results?

But there is no index between the two schemas to make a join, so it would require the two schemas to have the exact same format, which we ruled out by keeping their versions separate.

You could have it return two search results, one per schema, but that's a little clunky (and then you can't necessarily just concatenate those two results unless we ensure the schemas have the same layout).

For the `dregs ls` command its easy enough to do two queries and print the results. Just not sure if they can be returned robustly in a single object in the dataregistry package unless we ensure the schemas are exactly the same layout.

Any thoughts?

**Comment by JoanneBogart** [comment]
I hadn't thought this through and wasn't very clear - I was only thinking that results might include items from production, in particular production dependencies.  So if you ask for dependencies of a particular non-production dataset, the code should look at the execution for that dataset (always in the same schema) and the inputs attached to it, which could come either from the same schema or the production schema. I guess any production (dependency) datasets or columns from them would have to be qualified with "production".  Is that doable?  
In the case of returning dependencies, what exactly do we return?  I would think just the id.   But since those ids can now come from two different tables, they should be returned in separate lists (or something), say called `dependencies` and `production_dependencies`.
