### ISSUE TITLE
Bumping datasets with version suffix

### ISSUE THREAD

**Issue by stuartmcalpine** [LSSTDESC/dataregistry#90]
How are we expecting the bumping of datasets with version suffixes to work?

Currently we don't do what I thought (the suffix is essentially only used to look up the dataset).

Should "v1.1.1-test" patch bump to "v1.1.2-test", currently the suffix is lost after bumping

**Comment by JoanneBogart** [comment]
I don't think it makes sense to bump datasets with a suffix.     The suffix might be something like rc2, in which case "bump" could mean change to rc3, but we don't know that and we can't check for all plausible conventions.   The structure is totally up to the user.  I think we raise `ValueError`, just as is done for other bad input parameters.

**Comment by stuartmcalpine** [comment]
Addressed in #97 

> Decided we do not want to deal with how do auto-bump a dataset that has a suffix.

Therefore if the user tries to auto-bump a dataset with a suffix an error is raised.

A user can work with version suffixes and bumping manually, when registering the updated dataset they specify the version and suffix manually rather than trying to auto bump.
